akhil/urls.py
# djauth/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.views.generic.base import TemplateView
from filebrowser.sites import site
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='home:home', permanent=False)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^admin/filebrowser/', include(site.urls)),
   	url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^news/', include('committee.urls')),
    url(r'^gallery/',include('gallery.urls')),
    url(r'^pdf/',include('pdf.urls')),
    url(r'^home/',include('home.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^users/', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

committee/urls.py
from django.conf.urls import url
from . import views
app_name = "committee"
urlpatterns = [
    url(r'^$', views.resource_list, name='resource_list'),
    url(r'^resource/(?P<pk>\d+)$', views.ResourceDetail.as_view(), name='resource_detail'),
]

gallery/urls.py
from django.conf.urls import url
from . import views
app_name = "gallery"
urlpatterns = [
	url(r'^$', views.new_image_list, name='new_image_list'), 
    # url(r'^new/$', views.ImageList.as_view(), name='image_list'),
]

pdf/urls.py
from django.conf.urls import url
from . import views
app_name = "pdf"
urlpatterns = [
    url(r'^$', views.pdf_list, name='pdf_list'),
    
]

templates/includes/footer.html
<div class="text-center center-block space_top bg-red">
           <a class="navbar-brand left_side_space white" href="#">अखिल (क्रान्तिकारी)</a>
            <h5 class = "white">Contact us at</h5>
            
                <a href="https://www.facebook.com/bootsnipp"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
                 <a href="https://twitter.com/bootsnipp"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
                 <a href="https://plus.google.com/+Bootsnipp-page"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a>
                 <a href="mailto:bootsnipp@gmail.com"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
</div>

templates/includes/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-red fixed-top padding-left-0  padding-top-bottom-2">
      <div class="container-fluid padding-left-0">
        <div class = 'header_white'>
          <img src="{% static 'images/student_flag_small.png' %}" class="header-img" alt="Cinque Terre">
            <a class=" navbar-brand left_side_space title_text" href="#">अखिल (क्रान्तिकारी)</a>
          </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home:home' %}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'committee:resource_list' %}">News</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pdf:pdf_list' %}">Notices</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'gallery:new_image_list' %}">Gallery</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                
                <a class ="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'signup' %}">Register</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
</nav>