akhil/urls.py
# djauth/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.views.generic.base import TemplateView
from filebrowser.sites import site
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='home:home', permanent=False)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^admin/filebrowser/', include(site.urls)),
   	url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^news/', include('committee.urls')),
    url(r'^gallery/',include('gallery.urls')),
    url(r'^pdf/',include('pdf.urls')),
    url(r'^home/',include('home.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^users/', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url
from . import views
app_name = "home"
urlpatterns = [
	url(r'^$', views.home, name='home'), 
    # url(r'^new/$', views.ImageList.as_view(), name='image_list'),
]

pdf/urls.py
from django.conf.urls import url
from . import views
app_name = "pdf"
urlpatterns = [
    url(r'^$', views.pdf_list, name='pdf_list'),
    
]

home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import datetime
from django.db import models
# from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser

class Posts(models.Model):
	name = models.TextField(max_length = 100)
	def __str__(self):
		return self.name

class Role(models.Model):
	name = models.TextField(max_length = 100)
	def __str__(self):
		return self.name

class CustomUser(AbstractUser):
    # user = models.OneToOneField(User, on_delete=models.CASCADE)
    membership_no = models.IntegerField(blank = True, null = True, unique = True)
    educational_institude = models.CharField(max_length = 300,blank = True)
    date_of_issue = models.DateField(blank=False, null = False, default = datetime.date(1994,6,30))
    confirmed = models.BooleanField(default = False)
    # birth_date = models.DateField(null=True, blank=True)
    post= models.ForeignKey(Posts,default = 1)
    role= models.ForeignKey(Role,default = 1)

# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         UserDetails.objects.create(user=instance)

# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.profile.save()

home/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views.generic import ListView

from committee.models import *
from pdf.models import *

# Create your views here.
def home(request):
	news = Resource.objects.order_by("-date_created")	
	reports = Pdf.objects.order_by("-date_created")
	return render(request, 'home.html',{
        'news': news,
        'reports' : reports,
        })


# Create your views here.

templates/base.html
<!-- templates/base.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">
  <title>{% block title %}Login{% endblock %}</title>
  	{% block stylesheets %}
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/gallery-grid.css' %}">
    {% endblock %}
    <style>
      body {
        padding-top: 54px;
        padding-bottom : 0px;
      }
      @media (min-width: 992px) {
        body {
          padding-top: 56px;
        }
      }

    </style>

</head>
<body>
	  	
  <main>

    {% block content %}
    {% endblock %}
  </main>
   {% block scripts %}
   <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}
{% block stylesheets %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
{% endblock %}
{% block content %}

	{% include "includes/navbar.html" %}  
	<div class="container gallery-container">
		<div id="bg">
	  		<img src="{% static 'images/raising_hands.jpg' %}" alt="">
		</div>
	      <div class="row space_top">
	        <div class="col-md-6 col-sm-12 president_border">
					<div class = "row">
			          <div class = "col-md-4 col-sm-12">
			          	<img class="divcircle imagepresident" src="{% static 'images/prachanda.jpg' %}" alt=""></a>
			          </div>
			          <div class="col-md-8 col-sm-12">
			            
			            <div class="">
			              <h4 class="message_presi_title">
			                Message From President
			              </h4>
			              <p class="message_presi ">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
			            </div>
			          </div>
			        </div>
	        </div>
	        
	        <div class="col-md-6 col-sm-12">
				<div class = "row">
			          <div class = "col-md-4 col-sm-12">
			          	<img class="divcircle imagepresident" src="{% static 'images/prachanda.jpg' %}" alt=""></a>
			          </div>
			          <div class="col-md-8 col-sm-12">
			            
			            <div class="">
			              <h4 class="message_presi_title">
			                Message From President
			              </h4>
			              <p class="message_presi ">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna variThe government on Friday sent a letter to the election body, asking it to start preparations for the local polls. The EC meeting on the same day decided that the letter lacked clarity on the date and whether the elections would be held for the old or a new structure of the local bodies.
			              </p>
			            </div>
			          </div>
			        </div>	
	        </div>

	      </div>
	     	<div class = "title space_top bg-black padding-2 color-white news_title mes">
	     		<h3>
	     			Latest Reports
	     		</h3>
	     	</div>
	     <div class = "row space_top">
	     	{% for pdf in reports|slice:":4" %}
	     		<div class = "col-md-3 col-sm-6 border-right">
		     		<div class = "small_title news_title">
		     			<h5>
		     				{{ pdf.name }}
		     			</h5>
		     		</div>
		     		<div class = 'pdf_link news_title'>
		     			<a href = "{{ pdf.pdf.url }}"><img src = "{% static 'images/pdf_icon.png' %}" alt = "{{ pdf.pdf.filename }}"/></a>
		     		</div>
	     		</div>	
	     	{% endfor %}
	     	<!-- <div class = "col-md-3 col-sm-6 border-right">
	     		<div class = "small_title news_title">
	     			<h5>
	     				Sample Report
	     			</h5>
	     		</div>
	     		<div class = 'pdf_link news_title'>
	     			<a href = "#"><img src = "{% static 'images/pdf_icon.png' %}" /></a>
	     		</div>
	     	</div>
	     	<div class = "col-md-3 col-sm-6 border-right">
	     		<div class = "small_title news_title">
	     			<h5>
	     				Sample Report
	     			</h5>
	     		</div>
	     		<div class = 'pdf_link news_title'>
	     			<a href = "#"><img src = "{% static 'images/pdf_icon.png' %}" /></a>
	     		</div>
	     	</div>
	     	<div class = "col-md-3 col-sm-6 border-right">
	     		<div class = "small_title news_title">
	     			<h5>
	     				Sample Report
	     			</h5>
	     		</div>
	     		<div class = 'pdf_link news_title'>
	     			<a href = "#"><img src = "{% static 'images/pdf_icon.png' %}" /></a>
	     		</div>
	     	</div>
	     	<div class = "col-md-3 col-sm-6">
	     		<div class = "small_title news_title">
	     			<h5>
	     				Sample Report
	     			</h5>
	     		</div>
	     		<div class = 'pdf_link news_title'>
	     			<a href = "#"><img src = "{% static 'images/pdf_icon.png' %}" /></a>
	     		</div>
	     	</div>
 -->
	     </div>
	    <div class = "title space_top news_title bg-black padding-2 color-white">
	     		<h3>
	     			Latest News
	     		</h3>
	     	</div>
	     <div class = "row space_top space_bottom">
	     	{% for article in news|slice:":4" %}
	     		<div class = "col-md-3 col-sm-6 border-right ">
		     		<div class = "small_title news_title">
		     			<h5>
		     				{{ article.title }}
		     			</h5>
		     		</div>
		     		<div class = "details">
		     			News of {{ article.committee.name }} published at {{ article.date_created }}
		     		</div>
		     		<div class = 'news_content'>
		     			{{ article.content|safe|truncatewords:40 }}

		     			<a herf = "{{article.get_absolute_url}}"><span class = "color-red">Read More</span></a>
		     		</div>
	     		</div>
	     	{% endfor %}

	     	<!-- <div class = "col-md-3 col-sm-6 border-right ">
	     		<div class = "small_title news_title">
	     			<h5>
	     				Sample News
	     			</h5>
	     		</div>
	     		<div class = 'news_content'>
	     			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odi Lorem ipsum dolor sit amet,Lorem ipsum dolor sit amet,
	     			<a herf = "#"><span class = "color-red">Read More</span></a>
	     		</div>
	     	</div>
	     	<div class = "col-md-3 col-sm-6 border-right">
	     		<div class = "small_title news_title">
	     			<h5>
	     				Sample News
	     			</h5>
	     		</div>
	     		<div class = 'news_content'>
	     			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odi Lorem ipsum dolor sit amet,Lorem ipsum dolor sit amet,
	     			<a href = "#"><span class = "color-red">Read More</span></a>
	     		</div>
	     	</div>
	     	<div class = "col-md-3 col-sm-6 border-right ">
	     		<div class = "small_title news_title">
	     			<h5>
	     				Sample News
	     			</h5>
	     		</div>
	     		<div class = 'news_content'>
	     			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odi Lorem ipsum dolor sit amet,Lorem ipsum dolor sit amet,<a href="#"><span class = "color-red">Read More</span></a>
	     		</div>
	     	</div>
	     	<div class = "col-md-3 col-sm-6 ">
	     		<div class = "small_title news_title">
	     			<h5>
	     				Sample News
	     			</h5>
	     		</div>
	     		<div class = 'news_content'>
	     			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odi Lorem ipsum dolor sit amet,Lorem ipsum dolor sit amet,
	     			<a href = "#"><span class = "color-red">Read More</span></a>
	     		</div>
	     	</div>
 -->
	     </div>
		
    </div>
    {% include "includes/footer.html" %}  
	
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% load static %}
	{% block title %}Sign Up{% endblock %}
	{% block stylesheets %}
		{{ block.super }}
		<link rel="stylesheet" href="{% static 'css/login.css' %}">
	{% endblock %}
{% block content %}
	 <!--  <h2>Sign up</h2>
	  <form method="post">
	    {% csrf_token %}
	    {{ form.as_p }}
	    <button type="submit">Sign up</button>
	  </form> -->

  	<div class="register-page greater_width">
				  <div class = "dbpedia">
				  	Register
				  </div>
				  <div class="form greater_max_width">
					  	 <form  class="login-form" method = "POST">
					 
    						{% csrf_token %}
						  	 <input type="text" placeholder="Enter Username" name = 'username' autofocus required id="id_username" maxlength="150"/>
						  	 <span class="helptext">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span>
						  	 <input type="text" placeholder = "Enter First Name" name="first_name" id="id_first_name" maxlength="30" />
						  	 <input type="text" name="last_name" id="id_last_name" maxlength="30" placeholder = "Enter Last Name" />
						  	 <input type="password" name="password1" required id="id_password1" placeholder="Enter Password" /> 

						  	 <span class="helptext">
						  	 	<ul><li>Your password can&#39;t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can&#39;t be a commonly used password.</li><li>Your password can&#39;t be entirely numeric.</li></ul>
						  	 </span>
						  	 <input type="password" name="password2" required id="id_password2" placeholder="Re-Enter The Password" /> 

						  	 <span class="helptext">Enter the same password as before, for verification.</span>

						  	 <input type="email" name="email" id="id_email" maxlength="254" placeholder="Enter Email Address" />

						  	 <input type="text" name="educational_institude" id="id_educational_institude" maxlength="300" placeholder="Enter Educational Institute" />
				  			 <input type="text" name="date_of_issue" required id="id_date_of_issue" placeholder="Enter Date Of Issue" />
				  			 <button type = "submit" >login</button>

				  		</form>
				  </div>
	</div>

{% endblock %}